# Generated by Django 5.1.4 on 2024-12-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chromebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=30)),
                ('asset_id', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=120)),
            ],
        ),
    ]
