# Generated by Django 5.1.4 on 2024-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=120)),
                ('device', models.CharField(max_length=120)),
                ('date_of_occurance', models.DateField()),
                ('tech', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('ticket_number', models.CharField(max_length=30)),
                ('tech_notes', models.TextField()),
            ],
        ),
    ]
