# Generated by Django 5.1.4 on 2025-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='device',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tech',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='ticket_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
